# =============================================================================
# BASE CONFIGURATION
# =============================================================================

version: "3.7"

# =============================================================================
# SERVICES
# =============================================================================

services:

# =============================================================================
# NOTIFICATIONS
# =============================================================================

  notifications:
    container_name: ${CONTAINER_NAME}
    env_file: ./.env
    build:
      context: ./${PATH_DOCKERFILE}
      dockerfile: Dockerfile
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "20"
    networks:
      - notifications

# =============================================================================
# NETWORKS
# =============================================================================

networks:
  notifications:
